version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=news
      - POSTGRES_PASSWORD=news
      - POSTGRES_DB=news
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "5432", "-U", "news"]
      interval: 5s
      timeout: 5s
      retries: 3
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    environment:
      - ALLOW_RESET=True
    ports:
      - 8500:8000
  api:
    build:
      context: ./news_model
    env_file: .env
    depends_on:
      - chroma
    ports:
      - 80:80
volumes:
  postgres_data:
  index_data:
